database:
   driver: "org.h2.Driver"
   url: "jdbc:h2:./plugins/MaxBans/storage"
   user: "root"
   password: "password"
   show-sql: false

offline: false

warnings:
   penalties:
     1: "tell {{name}} This is your first warning"
     2: "tell {{name}} This is your final warning"
     3: "ban {{name}} 1 hour Warning limit reached:\n{{reason|No reason given}}"
   strikes: 3
   duration: "3 days"

chat-commands: []